### ISSUE TITLE
I can't see another user cam, but their chat is live.

### ISSUE THREAD

**Issue by ImBIOS** [huseyn0w/Fast-Connect#1]
My 1st Laptop:
Windows 10 Ver 2004
Chrome Version 89.0.4389.128

My 2nd Gadget:
Android 8
Chrome 90.0.4430.66

How to Reproduce:
1. First I made a conf with my laptop
2. then My second gadget open the same room
3. Here we not see each other, but the chat is live

**Comment by huseyn0w** [comment]
Dear @ImBIOS , thanks for your comment! The issue you mentioned happens sometimes, due to free hosting I'm using as Demo, and unstable internet connection. In that case, just refresh the page, and please make sure that you and your partner have the same ID to connect.
